[build]
target = "thumbv7em-none-eabihf"   # Cortex-M4F with hardware FPU (STM32F405)

[target.thumbv7em-none-eabihf]
runner = "./flash.sh"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"
